# Generated by Django 6.0.4 on 2026-04-25 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campus', models.CharField(default='BMCC', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('MBJ', 'Standard MBJ Caterer'), ('OON', 'Out of Network')], max_length=3)),
                ('event_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending SGA Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('quote_1', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('quote_2', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('quote_3', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='clubs.club')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
