# Generated by Django 6.0.4 on 2026-04-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campus', models.CharField(default='BMCC', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g., Spring 2026', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending SGA Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('RETURNED', 'Returned for Edits')], default='PENDING', max_length=15)),
                ('previous_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_count', models.CharField(max_length=50)),
                ('community_enhancement', models.TextField(help_text='How the club enhanced the college community.')),
                ('activities', models.JSONField(default=list, help_text='Array of planned events and their budgets.')),
                ('non_activity_items', models.JSONField(default=list, help_text='Array of promotional items, supplies, etc.')),
                ('total_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_proposals', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=254)),
                ('emplid', models.CharField(help_text='8-digit CUNY EMPLID', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clubs.event')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('MBJ', 'Standard MBJ Caterer'), ('OON', 'Out of Network')], default='MBJ', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending SGA Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('setup_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('headcount', models.IntegerField(blank=True, null=True)),
                ('food_items', models.TextField(blank=True, help_text='List the packages and specific items ordered.', null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quote_1', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('quote_2', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('quote_3', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='clubs.club')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
