# Generated by Django 6.0.4 on 2026-04-25 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='food_items',
            field=models.TextField(blank=True, help_text='List the packages and specific items ordered.', null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='setup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order_type',
            field=models.CharField(choices=[('MBJ', 'Standard MBJ Caterer'), ('OON', 'Out of Network')], default='MBJ', max_length=3),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending SGA Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
