# Generated by Django 6.0.4 on 2026-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetproposal',
            name='reviewer_comment',
            field=models.TextField(blank=True, default='', help_text='Comments from advisor/SGA reviewer.'),
        ),
    ]
