# Generated by Django 6.0.4 on 2026-04-25 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_foodorder_contact_name_foodorder_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g., Spring 2026', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending SGA Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('RETURNED', 'Returned for Edits')], default='PENDING', max_length=15)),
                ('previous_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_count', models.CharField(max_length=50)),
                ('community_enhancement', models.TextField(help_text='How the club enhanced the college community.')),
                ('activities', models.JSONField(default=list, help_text='Array of planned events and their budgets.')),
                ('non_activity_items', models.JSONField(default=list, help_text='Array of promotional items, supplies, etc.')),
                ('total_requested', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_proposals', to='clubs.club')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
